apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
  namespace: tpg
  labels:
    app: employee-service
    group: general
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
        group: general
        version: v1
    spec:
      containers:
        - name: employee-service
          image: employee-service:latest
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 60